# -*- coding: utf-8 -*-
import random

JOBS = [
    {
        "company_avatar": "/theme/images/jobs/ef.jpeg",
        "company_name": "e-Frontiers",
        "position": "Senior Python Developer",
        "description": "Buscamos desarrolladores con experiencia en Python para trabajar remotamente desde cualquier país europeo para trabajar en una empresa tecnológica con producto propio, una potente herramienta analítica, que opera en diferentes países y que ya está siendo considerada como el nuevo unicornio tecnológico español.",
        "location": "España/ 100% remoto",
        "skills": [
            "python",
            "unittest",
            "docker",
            "kubernetes",
            "kafka",
            "spark",
            "inglés alto",
        ],
        "salary": "50.000 - 70.000 €",
        "url": "https://e-frontiers.ie/find-a-job/senior-python-developer-7348/",
        "email": "alejandro.pino@e-frontiers.ie",
    },
    {
        "company_avatar": "/theme/images/jobs/ef.jpeg",
        "company_name": "e-Frontiers",
        "position": "Senior Python Mid-Senior",
        "description": "Estás descubriendo el poder de Python, pero quieres explorar todas sus posibilidades. Tenemos vacantes abiertas en una empresa enfocada al desarrollo de múltiples aplicaciones aplicadas a las finanzas: herramientas Fintech! Si te gusta cacharrear con el código tenemos que hablar :D",
        "location": "Pozuelo de Alarcón (Madrid) / Semirremoto",
        "skills": ["python", "flask", "docker", "kubernetes", "sql"],
        "salary": "30.000€ – 42.000€",
        "url": "https://e-frontiers.ie/find-a-job/python-developer-mid-senior-7330/",
        "email": "alejandro.pino@e-frontiers.ie",
    },
    {
        "company_avatar": "/theme/images/jobs/ef.jpeg",
        "company_name": "e-Frontiers",
        "position": "Python Developer EUROPE – 100% REMOTE",
        "description": "Te gusta trabajar con Python, desde casa, desde cualquier lugar de Europa… ¡Tenemos que hablar! Tenemos diversas oportunidades abiertas para desarrolladores Python en empresas de producto propio, con sede principalmente en España e Irlanda, esperándote.",
        "location": "Europa / Remoto 100%",
        "skills": [
            "python",
            "django",
            "flask",
            "sql",
            "docker",
            "aws/azure",
            "inglés alto",
        ],
        "salary": "40.000€ – 60.000€",
        "url": "https://e-frontiers.ie/jobs/7799/",
        "email": "alejandro.pino@e-frontiers.ie",
    },
    {
        "company_avatar": "/theme/images/jobs/ef.jpeg",
        "company_name": "e-Frontiers",
        "position": "Python Developer IRELAND",
        "description": "We are looking for a Python Developer to join an Investment Management Firm in Dublin. You will be working within their Infrastructure Reliability Engineering team. Their goal is to ensure platform reliability and operational agility by developing visualizations, dashboards, and tools that reveal insights in data.",
        "location": "Irlanda / Ambas opciones 100% Remoto y Presencial",
        "skills": [
            "python",
            "django",
            "flask",
            "sql",
            "docker",
            "aws/azure",
            "inglés alto",
        ],
        "salary": "40.000€ – 60.000€",
        "url": "https://e-frontiers.ie/find-a-job/python-developer-7708/",
        "email": "lisa.cappelli@e-frontiers.ie",
    },
    {
        "company_avatar": "/theme/images/jobs/alea.jpeg",
        "company_name": "Alea",
        "position": "Senior Developer",
        "description": "Buscamos a alguien de backend. Pero que no le tenga miedo a sistemas, redes, negocio... Con experiencia en desarrollo de aplicaciones con buenas prácticas (XP, arquitecturas limpias o hexagonales), testing (TDD) y que le guste mucho trabajar en equipo puesto que hacemos pairing",
        "location": "Madrid / Remoto",
        "skills": [
            "python",
            "testing",
            "clean code",
            "arquitecturas limpias",
            "colaboración",
            "trabajo en equipo",
            "empatía",
            "proactividad",
        ],
        "salary": "40.000€ – 50.000€",
        "url": "https://aleasoluciones.notion.site/Forma-parte-del-equipo-p-blica-968223e26cc84d94bb9d0efc8038535e",
        "email": "desarrollo@alea-soluciones.com",
    },
    {
        "company_avatar": "/theme/images/jobs/travelperk.png",
        "company_name": "TravelPerk",
        "position": "Software Engineer",
        "description": "We are looking for product-oriented software engineers with 3+ years experience in any web programming language. Come and join us to work in one of the fastest growing scale-ups in the world revolutionizing the business travel industry.",
        "location": "Barcelona / Berlin / London / Birmingham hybrid",
        "skills": [
            "python",
            "django",
            "tornado",
            "react",
            "aws",
            "docker",
            "inglés alto",
        ],
        "salary": "50.000€ – 65.000€",
        "url": "https://www.travelperk.com/job-application/?gh_jid=3242844",
    },
    {
        "company_avatar": "/theme/images/jobs/travelperk.png",
        "company_name": "TravelPerk",
        "position": "Senior Software Engineer",
        "description": "We are looking for product-oriented software engineers with 3+ years experience in any web programming language. Come and join us to work in one of the fastest growing scale-ups in the world revolutionizing the business travel industry.",
        "location": "Barcelona / Berlin / London / Birmingham hybrid",
        "skills": [
            "python",
            "django",
            "tornado",
            "react",
            "aws",
            "docker",
            "inglés alto",
        ],
        "salary": "65.000€ – 90.000€",
        "url": "https://www.travelperk.com/job-application/?gh_jid=3242303",
    },
    {
        "company_avatar": "/theme/images/jobs/travelperk.png",
        "company_name": "TravelPerk",
        "position": "Engineering Manager",
        "description": "We are looking for people-oriented Engineering Managers with 3+ years experience in directly managing engineers to join us at a hyper-growth period. We’ve recently raised $115 million, making us a unicorn! Come and join us in revolutionizing the global business travel industry.",
        "location": "Barcelona / Berlin / London / Birmingham hybrid",
        "skills": ["management", "career path", "leadership",],
        "salary": "75.000€ – 95.000€",
        "url": "https://www.travelperk.com/job-application/?gh_jid=3958248",
    },
    {
        "company_avatar": "/theme/images/jobs/celtiberian.png",
        "company_name": "Celtiberian",
        "position": "Junior Full-Stack developer (Javascript/Python)",
        "description": "¿Alguna vez has deseado trabajar con startups de la mismísima California? En Celtiberian buscamos ingenieros con alguna experiencia en el desarrollo de software interesados en dominar el entorno de Javascript y Python, además de apasionados del conocimiento tecnológico.",
        "location": "Granada / Remoto",
        "skills": [
            "JavaScript",
            "Python",
            "Django",
            "React",
            "Node.js",
            "React Native",
            "Inglés alto",
        ],
        "salary": "24.000€ - 36.000€",
        "url": "https://es.linkedin.com/company/celtiberian",
        "email": "lorena@celtiberian.es",
    },
    {
        "company_avatar": "/theme/images/jobs/celtiberian.png",
        "company_name": "Celtiberian",
        "position": "Senior Full-Stack developer (Javascript/Python)",
        "description": "Si además de ser un desarrollador Full-Stack experimentado con los ecosistemas de Javascript y Python, estabas buscando una oportunidad para trabajar con startups en entornos internacionales y dinámicos, tenemos una propuesta interesante para tí.",
        "location": "Granada / Remoto",
        "skills": [
            "JavaScript",
            "Python",
            "Django",
            "React",
            "Node.js",
            "React Native",
            "Inglés alto",
        ],
        "salary": "32.000€ - 45.000€",
        "url": "https://es.linkedin.com/company/celtiberian",
        "email": "lorena@celtiberian.es",
    },
    {
        "company_avatar": "/theme/images/jobs/celtiberian.png",
        "company_name": "Celtiberian",
        "position": "DevOps Engineer",
        "description": "¿Te apasiona el DevOps y te llama la atención trabajar para startups internacionales? En Celtiberian podrás cubrir ambas demandas. Somos una consultora de software comprometida con los servicios de calidad y la formación constante en las tecnologías más punteras.",
        "location": "Granada / Remoto",
        "skills": [
            "Kubernetes",
            "Docker",
            "Python",
            "JavaScript",
            "AWS",
            "Inglés alto",
        ],
        "salary": "35.000€ - 45.000€",
        "url": "https://es.linkedin.com/company/celtiberian",
        "email": "lorena@celtiberian.es",
    },
    {
        "company_avatar": "/theme/images/jobs/intelygenz.png",
        "company_name": "Intelygenz",
        "position": "Data Scientist - ML",
        "description": "We’re looking for a Machine Learning Engineer to bring their expertise to some great projects, learn in a friendly, collaborative environment, and innovate with us. You will design and implement end-to-end data pipelines, being part of an agile team of amazing developers.",
        "location": "Madrid / Remoto",
        "skills": ["ML", "Python", "Golang", "Docker", "SQL", "Protobuf",],
        "salary": "36.000€ - 45.000€",
        "url": "https://intelygenz.com/job/731838/",
    },
    {
        "company_avatar": "/theme/images/jobs/intelygenz.png",
        "company_name": "Intelygenz",
        "position": "Data Scientist",
        "description": "As a Data Scientist your goals will be organized in two areas. Industry: process automation. Laboratory: research and testing state-of-the-art techniques and solutions to keep improving our skills and sharing with the community our knowledge and proof of concepts.",
        "location": "Madrid / Remoto",
        "skills": [
            "Numpy",
            "Pandas",
            "Scikit-learn",
            "PyTorch/Tensorflow",
            "Deep Reinforcement Learning",
            "NLP",
        ],
        "salary": "36.000€ - 45.000€",
        "url": "https://intelygenz.com/job/440392/",
    },
    {
        "company_avatar": "/theme/images/jobs/intelygenz.png",
        "company_name": "Intelygenz",
        "position": "Tech Lead Automation",
        "description": "Our next Technical Lead is very skilled in Python and/or Golang and has 5 years of experience deploying and evolving software in production environments. Also, Scalable Architectures are part of your day and Good development practices are a must for you.",
        "location": "Madrid / Remoto",
        "skills": ["Python", "Golang", "Databases", "DevOps", "Docker",],
        "salary": "50.000€ - 60.000€",
        "url": "https://intelygenz.com/job/814833/",
    },
    {
        "company_avatar": "/theme/images/jobs/intelygenz.png",
        "company_name": "Intelygenz",
        "position": "Python Developer",
        "description": "The Python Developer we are looking for has at least 3 years of experience, good developement practices and enjoy working in an agile and collaborative environment. Also, knows Docker and/or Kubernetes, ATDD and is able to communicate in English.",
        "location": "Madrid / Remoto",
        "skills": ["Python", "Docker", "TDD", "JavaScript",],
        "salary": "32.000€ - 40.000€",
        "url": "https://intelygenz.com/job/649170/",
    },
    {
        "company_avatar": "/theme/images/jobs/holaluz.png",
        "company_name": "Holaluz",
        "position": "Data Architect",
        "description": "🍼 Nursery inhouse<br/>🚀 Desarrollo profesional sin límites en una empresa apasionante y un equipo con desafíos constantes<br/>🏡 Horario flexible y posibilidad de trabajo a distancia de forma habitual.<br/>🌊 Ubicaciones de las oficinas a primera linea de mar<br/>💪 Yoga y Crossfit inhouse",
        "location": "Híbrida (Barcelona)",
        "skills": ["AWS", "Snowflake o Redshift", "Python", "SQL", "Airflow",],
        "salary": "60.000 € - 85.000 €",
        "url": "https://apply.workable.com/holaluz/j/478A031C7A/",
        "email": "ariadna.garriga@holaluz.com",
    },
    {
        "company_avatar": "/theme/images/jobs/holaluz.png",
        "company_name": "Holaluz",
        "position": "Senior Data Engineer",
        "description": "En Holaluz estamos buscando a un/a Senior Data Engineer para ser responsable de la integración, arquitectura y mantenimiento de los Datos con las tecnologías de la casa AWS, Pentaho Kettle, Python, Java, Scala, MySQL, SQL, MongoDB y Airflow. ¿Te interesa? ¡Sigue leyendo! 🙂",
        "location": "Híbrida (Barcelona)",
        "skills": [
            "AWS",
            "Pentaho Kettle",
            "Python",
            "Java",
            "Scala",
            "MySQL",
            "SQL",
            "MongoDB",
            "Airflow",
        ],
        "salary": "40.000 € - 50.000 €",
        "url": "https://holaluz.workable.com/backend/jobs/2565347/",
        "email": "ariadna.garriga@holaluz.com",
    },
    {
        "company_avatar": "/theme/images/jobs/trustyou.jpeg",
        "company_name": "TrustYou",
        "position": "Professional Python Developer",
        "description": "Imagine a workplace that allows you to own your own product and where your ideas will be heard and implemented. Imagine an environment where your performance makes a difference, not just within the company itself but for billions of travelers worldwide! That place is TrustYou.",
        "location": "Madrid / Munich / Cluj-Napoca / Remote",
        "skills": [
            "Python 3",
            "asynchronous programming",
            "PostgreSQL",
            "unit-testing",
            "Web APIs",
        ],
        "salary": "40.000€ - 60.000€",
        "url": "https://jobs.lever.co/trustyou/5732c644-7245-4f41-8ec1-50d819cf438a",
    },
    {
        "company_avatar": "/theme/images/jobs/trustyou.jpeg",
        "company_name": "TrustYou",
        "position": "Professional Engineer - Backend",
        "description": "Imagine a workplace that allows you to own your own product and where your ideas will be heard and implemented. Imagine an environment where your performance makes a difference, not just within the company itself but for billions of travelers worldwide! That place is TrustYou.",
        "location": "Spain / Germany / Romania / European Union (Remote)",
        "skills": ["Ruby on Rails", "Javascript", "PostgreSQL", "TDD",],
        "salary": "40.000€ - 70.000€",
        "url": "https://jobs.lever.co/trustyou/2ca76451-8c8a-43e6-ae54-93fdee798398",
    },
    {
        "company_avatar": "/theme/images/jobs/trustyou.jpeg",
        "company_name": "TrustYou",
        "position": "Senior Frontend Engineer",
        "description": "Imagine a workplace that allows you to own your own product and where your ideas will be heard and implemented. Imagine an environment where your performance makes a difference, not just within the company itself but for billions of travelers worldwide! That place is TrustYou.",
        "location": "Spain / Germany / Romania / European Union (Remote)",
        "skills": [
            "frontend",
            "React",
            "reusable UIs",
            "Redux/MobX",
            "NodeJS",
            "any backend language",
        ],
        "salary": "50.000€ - 70.000€",
        "url": "https://jobs.lever.co/trustyou/8f27c517-587f-4832-9d79-dbf48a5a5134",
    },
    {
        "company_avatar": "/theme/images/jobs/nucleoo.jpeg",
        "company_name": "Nucleoo",
        "position": "Software Engineer",
        "description": "Here you will be part of one of the agile development teams working on large data projects using technologies such as Python, Angular, and MongoDB. You will work together with the Lead Developer and communicate with clients in English every day.",
        "location": "Híbrido/100% remoto",
        "skills": [
            "Python",
            "Angular",
            "React",
            "Vue.js",
            "SQL or No-SQL",
            "Jasmine/cypress/Jest",
            "Git",
            "Flask",
            "C#/.NET",
            "Gitlab",
            "Docker" "Terraform",
            "AWS/Azure",
        ],
        "salary": "20.000€ - 45.000€",
        "url": "https://nucleoo.com/careers/software-engineer-python/",
        "email": "hr@nucleoo.com",
    },
    {
        "company_avatar": "/theme/images/jobs/nucleoo.jpeg",
        "company_name": "Nucleoo",
        "position": "FullStack Engineer",
        "description": "We are looking for an experienced and talented fullstack engineer  with +3 years experience for developing enterprise scale software.",
        "location": "Hibrido/100% remoto",
        "skills": [
            "English",
            "React",
            "JavaScript",
            "Typescript",
            "HTML",
            "CSS",
            "LESS",
            "computer systems",
            "algorithms",
            "flows",
            ".net",
            "c#",
            "powershell",
            "XML",
        ],
        "salary": "25.000€ - 45.000€",
        "url": "https://nucleoo.com/careers/fullstack-engineer/",
        "email": "hr@nucleoo.com",
    },
    {
        "company_avatar": "/theme/images/jobs/nucleoo.jpeg",
        "company_name": "Nucleoo",
        "position": "Quality Assurance Engineer",
        "description": "Nucleoo is looking for an experienced and talented Test Engineer who’s proficient in testing of enterprise scale software and automation of tests. ",
        "location": "Híbrido/100% remoto",
        "skills": [
            "Testrail",
            "Ttest automation code",
            "C#",
            "PowerShell",
            "Issues/bugs (Jira)",
            "Confluence",
            "Load tests",
            "Testing",
            "Development",
        ],
        "salary": "20.000€ - 45.000€",
        "url": "https://nucleoo.com/careers/quality-assurance-engineer/",
        "email": "hr@nucleoo.com",
    },
    {
        "company_avatar": "/theme/images/jobs/nucleoo.jpeg",
        "company_name": "Nucleoo",
        "position": ".Net developer",
        "description": "Nucleoo is looking for an experienced and talented Microsoft .NET Developer who’s proficient in developing enterprise scale software. ",
        "location": "Híbrida/100% remoto",
        "skills": [
            ".NET",
            "C#",
            "algorithms",
            "flows",
            "PowerShell",
            "XSLT",
            "DTD",
            "XSD",
            "XML Editors",
            "oXygen",
            "JustSystems XMetaL",
        ],
        "salary": "20.000€ - 45.000€",
        "url": "https://nucleoo.com/careers/net-developer/",
        "email": "hr@nucleoo.com",
    },
    {
        "company_avatar": "/theme/images/jobs/nucleoo.jpeg",
        "company_name": "Nucleoo",
        "position": "Javascript Engineer",
        "description": "Nucleoo is looking for a self- motivated, multi-tasker and team player engineer to join us in Granada. This is a fantastic opportunity to join a growing and innovative team.",
        "location": "Híbrida/100% remoto",
        "skills": [
            "Typescript",
            "ReactJS",
            "HTML",
            "CSS",
            "Angular",
            "Vue",
            "Cypress",
            "Node",
            "PostgreSQL",
            "AWS",
            "MongoDB",
            "Python",
        ],
        "salary": "20.000€ - 45.000€",
        "url": "https://nucleoo.com/careers/javascript-engineer/",
    },
    {
        "company_avatar": "/theme/images/jobs/ebury.jpeg",
        "company_name": "Ebury Partners UK, Ltd",
        "position": "Senior Mobile Developer - Full Remote",
        "description": "You'll take responsibility for the Mobile Apps development as part of  Channels ecosystem in Ebury. We need experience with building native iOS apps that delight users (Swift Code), writing applications in Flutter or react-Native, and good knowledge of Python.",
        "location": "Full Remote",
        "skills": ["Mobile", "IOS", "Flutter", "React-Native", "NodeJS", "Python"],
        "salary": "55.000€ - 80.000€",
        "url": "https://careers.ebury.com/jobs/1946971-senior-mobile-developer-full-remote",
        "email": "emma.casanova@ebury.com",
    },
    {
        "company_avatar": "/theme/images/jobs/ebury.jpeg",
        "company_name": "Ebury Partners UK Ltd.",
        "position": "Senior Python Developer",
        "description": "We have big experience developing complex sw systems; mainly work with Python/Django; our developers that can “build and run” services, are comfortable with dockerising the code, define standard REST endpoints, adding monitoring and alerting your services. SQL knowledge is a +",
        "location": "Full Remote",
        "skills": [
            "python",
            "django",
            "sql",
            "jenkins",
            "terraform",
            "sentry",
            "prometheus",
            "ELK",
            "Docker",
            "ECS",
            "Kubernetes",
            "kafka",
        ],
        "salary": "40.000€ - 80.000€",
        "url": "https://careers.ebury.com/jobs/1772667-senior-python-engineer-backend-remote",
        "email": "emma.casanova@ebury.com",
    },
    {
        "company_avatar": "/theme/images/jobs/kairos.jpeg",
        "company_name": "Kairos DS",
        "position": "Data Engineer",
        "description": "En Kairós DS buscamos personas, con perfiles desde profesionales a más junior, expertas en Data Engineer y con conocimientos de Python para formar parte de nuestra capacidad de Data & IA, liderada por Inés Huertas.",
        "location": "Remoto",
        "skills": [
            "Lambda",
            "Fargate",
            "ECS",
            "S3",
            "SNS",
            "GLUE",
            "ATHENA",
            "RDS",
            "IAM",
            "CLOUDFORMATION",
            "GIT",
            "CI/CD",
            "CI/CD",
            "Python",
            "Pandas",
            "SQLs",
        ],
        "salary": "45.000€ - 60.000€",
        "url": "https://jobs.kairosds.com/jobs/data-engineer-ntq3e-22",
        "email": "talento@kairosds.com",
    },
    {
        "company_avatar": "/theme/images/jobs/kairos.jpeg",
        "company_name": "Kairos DS",
        "position": "Azure Data Engineer",
        "description": "Buscamos personas, con perfiles desde profesionales a más junior, expertas en Data Engineer y con conocimientos de Azure para formar parte de nuestra capacidad de Data & IA, liderada por Inés Huertas.",
        "location": "Remoto",
        "skills": ["Data Modellling", "Spark/SQL/Python", "Event streaming (Kafka)",],
        "salary": "45.000€ - 60.000€",
        "url": "https://jobs.kairosds.com/jobs/azure-data-engineer-ntq3e-22",
        "email": "talento@kairosds.com",
    },
    {
        "company_avatar": "/theme/images/jobs/kairos.jpeg",
        "company_name": "Kairos DS",
        "position": "Data Engineer con Spark y Scala",
        "description": "En Kairós DS buscamos personas con experiencia como Data Engineer y con experiencia en Spark y Scala para formar parte de nuestra capacidad de Data & IA, liderada por Inés Huertas.",
        "location": "Remoto",
        "skills": ["Spark - Scala", "Spark", "CI/CD", "Jenkins"],
        "salary": "45.000€ - 60.000€",
        "url": "https://jobs.kairosds.com/jobs/data-engineer-con-spark-y-scala-ntq3ebb-22",
        "email": "talento@kairosds.com",
    },
    {
        "company_avatar": "/theme/images/jobs/alight.png",
        "company_name": "Alight",
        "position": "Data Scientist",
        "description": "We are looking for a strong and motivated Data Scientist to support our growing AI team. If you have experience on Python, ML and statistics we are looking for you!",
        "location": "Granada",
        "skills": ["Python", "ML", "Statistics"],
        "salary": "up to 40.000€",
        "url": "https://careers.alight.com/us/en",
        "email": "",
    },
    {
        "company_avatar": "/theme/images/jobs/alight.png",
        "company_name": "Alight",
        "position": "Automation Anywhere",
        "description": "We are expanding our automation implementation team. If you have some experience in automation with Python come help us to create some cool robots!",
        "location": "Granada",
        "skills": ["Python"],
        "salary": "up to 35.000€",
        "url": "https://careers.alight.com/us/en",
        "email": "",
    },
    ###
    {
        "company_avatar": "/theme/images/jobs/backmarket.jpeg",
        "company_name": "Back Market",
        "position": "Backend Engineer",
        "description": "We are looking for Backend Software Developers who will help to design, develop, and manage the technical functionalities related to the evolution and adaptation of our international business. If you have 2 years of experience and Python knowledge, reach out to us!",
        "location": "Remoto desde España, Francia o Alemania",
        "skills": ["Python", "clean code", "TDD", "BDD", "DDD", "SOLID"],
        "salary": "50.000€ - 100.000€",
        "url": "https://jobs.lever.co/backmarket/8294c358-89ff-4ffe-84ab-9b7c06d2a4c0",
        "email": "franco.de-udaeta@backmarket.com",
    },
    {
        "company_avatar": "/theme/images/jobs/novatec.jpeg",
        "company_name": "Novatec Software Engineering España SL",
        "position": "Site Reliability Engineer",
        "description": "Automation, automation! It’s no mistake – it’s the heart of Site Reliability Engineering. As a Site Reliability Engineer, you enable the growth, maintainability, and scalability of enterprise applications of our development teams.",
        "location": "Hibrida/remota + Granada",
        "skills": [
            "Kubernetes",
            "Docker",
            "Istio",
            "Terraform",
            "Git",
            "Bash",
            "Java",
            "Spring",
            "CI/CD",
            "AWS",
            "Azure",
            "GCP",
            "English",
        ],
        "salary": "30.000€ - 40.000€",
        "url": "https://www.novatec-gmbh.de/en/job/sredevgrx/",
        "email": "careers-spain@novatec-gmbh.de",
    },
    {
        "company_avatar": "/theme/images/jobs/novatec.jpeg",
        "company_name": "Novatec Software Engineering España SL",
        "position": "Principal Back-end Software Engineer",
        "description": "Have you always been looking for a team that strives for the latest technologies and live agile values while implementing them with customers?  We live DevOps! You not only develop features but also take care of building pipelines and other infrastructures.",
        "location": "Hibrida/remota + Granada",
        "skills": [
            "Spring / Spring Boot / Spring Cloud",
            "Kotlin",
            "Java",
            "Kubernetes",
            "Docker",
            "Terraform",
            "Helm",
            "Git",
            "Bash",
            "CI/CD",
            "English",
        ],
        "salary": "45.000€ - 60.000€",
        "url": "https://www.novatec-gmbh.de/en/job/backend-software-engineer-spain/",
        "email": "careers-spain@novatec-gmbh.de",
    },
    {
        "company_avatar": "/theme/images/jobs/cathedralsoftware.jpeg",
        "company_name": "Cathedral Software",
        "position": "Backend Developer",
        "description": "Consultoría de software en plena expansión, involucrada, entre otros, en proyectos de Big Data y BI para empresas multinacionales. Buscamos constantemente personas responsables y dinámicas, apasionadas de las nuevas tecnologías y amantes del trabajo en equipo.",
        "location": "Remoto 100% ó Hibrida (Málaga)",
        "skills": [
            "Python 3",
            "git/ mercurial",
            "Django",
            "Flask",
            "PostgreSQL or MySQL",
            "Docker",
            "Agile",
            "Scrum methodologies",
        ],
        "salary": "22.000€ - 50.000€",
        "url": "https://es.indeed.com/cmp/Cathedral-Software-Sl/jobs?jk=6f423f7e2b42e828&start=0",
        "email": "people@cathedralsw.com",
    },
    {
        "company_avatar": "/theme/images/jobs/cathedralsoftware.jpeg",
        "company_name": "Cathedral Software",
        "position": "Frontend Developer",
        "description": "Consultoría de software en plena expansión, involucrada, entre otros, en proyectos de Big Data y BI para empresas multinacionales. Buscamos constantemente personas responsables y dinámicas, apasionadas de las nuevas tecnologías y amantes del trabajo en equipo",
        "location": "Remoto 100% ó Hibrida (Málaga)",
        "skills": [
            "React",
            "Vue",
            "Angular 4+",
            "Git",
            "HTML y CSS",
            "TailwindCSS or Bootstrap 3+"
            "Postman",
            "Insomnia",
            "Agile",
        ],
        "salary": "22.000€ - 50.000€",
        "url": "https://es.indeed.com/cmp/Cathedral-Software-Sl/jobs?jk=b8ccbd3acaf18bf0&start=0",
        "email": "people@cathedralsw.com",
    },

    {
        "company_avatar": "/theme/images/jobs/bluetab.png",
        "company_name": "Bluetab, an IBM Company",
        "position": "Python Data Developer",
        "description": "Como Data Engineer experto en Python, sólo te pedimos que más allá de las ganas desarrollarte, seas una persona curiosa, inquieta, con ganas de enfrentarte a todo tipo de misiones y un poco geek y por qué no...experto en algunas tecnologías (abajo), lo demás lo ponemos nosotros:",
        "location": "presencial/remota/híbrida ",
        "skills": [
            "Python",
            "Pandas",
            "Flask",
            "Django",
            "SQL",
            "MySQL"
            "Oracle",
            "DevOps",
            "Docker",
            "Kubernetes",
            "Cloud",
            "Big Data",
        ],
        "salary": "30.000€ - 45.000€",
        "url": "https://www.linkedin.com/jobs/view/3237870143",
        "email": "guillermo.perez@bluetab.net",
    },

    {
        "company_avatar": "/theme/images/jobs/bluetab.png",
        "company_name": "Bluetab, an IBM Company",
        "position": "Big Data Engineer (Scala/Spark/PySpark)",
        "description": "Estamos buscando cracks del mundo del Dato (Big Data/Data Engineer), que le gusten los datos, la búsqueda minuciosa, el análisis y la tecnología. Si te sientes identificado/a con las tecnologías, no te lo pienses...¡te estamos esperando!",
        "location": "presencial/remota/híbrida ",
        "skills": [
            "Scala",
            "Spark",
            "PySpark",
            "Cloud",
            "AWS",
            "Azure"
            "SQL",
            "Big Data",
            "Databricks",
            "Hadoop",
            "HDFS",
            "YARN",
            "MapReduce",
        ],
        "salary": "30.000€ - 50.000€",
        "url": "https://www.linkedin.com/jobs/view/3200752210",
        "email": "guillermo.perez@bluetab.net",
    },
    {
        "company_avatar": "/theme/images/jobs/bluetab.png",
        "company_name": "Bluetab, an IBM Company",
        "position": "AWS/Azure Data Engineer",
        "description": "Ofrecemos la oportunidad de trabajar en entornos con un alto expertise tecnológico en el mundo Data&Cloud donde poder desarrollarse personal y profesionalmente, aprender, formarse y compartir experiencias tecnológicas, fomentando una filosofía de trabajo en equipo y cooperación.",
        "location": "presencial/remota/híbrida ",
        "skills": [
            "AWS",
            "Azure",
            "Python",
            "Cloud",
            "Big Data",
            "Scala"
            "Spark",
            "EMR",
            "S3",
            "CI/CD",
            "Terraform",
            "Docker",
            "Kubernetes",
            "DataBricks",
            "HDFS",
        ],
        "salary": "30.000€ - 50.000€",
        "url": "https://www.linkedin.com/jobs/view/3150132240",
        "email": "guillermo.perez@bluetab.net",
    },

    {
        "company_avatar": "/theme/images/jobs/kavehome.png",
        "company_name": "KAVE HOME",
        "position": "BACKEND DEVELOPER",
        "description": "In KAVE TECH we are looking for a BACKEND DEVELOPER to join our team! Be part of a team of more than 30 people with a lot of freedom to develop their skills and with the aim of becoming the technological reference in the furniture and decoration industry.",
        "location": "Remoto/híbrido",
        "skills": [
            "python",
            "django",
            "cloud",
            "docker",
            "kubernetes",
            "GCloud",
           
        ],
        "salary": "30.000€ - 50.000€",
        "url": "https://jobs.kavehome.com/jobs/backend-developer-h-m",
        "email": "amilena@kavehome.com",
    },

    {
        "company_avatar": "/theme/images/jobs/kavehome.png",
        "company_name": "KAVE HOME",
        "position": "DATA PRODUCT MANAGER",
        "description": "In KAVE TECH we are looking for a DATA PRODUCT MANAGER! You'll be responsible for defining the product strategy and its roadmap together with stakeholders, and optimising the resources of the team to guarantee the delivery of value.",
        "location": "híbrido",
        "skills": [
            "Roadmap",
            "Jira",
            "Hitos",
            "backlog",
            "stakeholders",
            "agile",
            "mvp",
           
        ],
        "salary": "30.000€ - 50.000€",
        "url": "https://jobs.kavehome.com/jobs/data-product-manager",
        "email": "amilena@kavehome.com",
    },

    {
        "company_avatar": "/theme/images/jobs/kavehome.png",
        "company_name": "KAVE HOME",
        "position": "E-COMMERCE PRODUCT OWNER",
        "description": "In KAVE TECH we are looking for an E-COMMERCE PRODUCT OWNER! You'll be responsible for defining the product strategy and its roadmap together with stakeholders, and optimising the resources of the team to guarantee the delivery of value.",
        "location": "HIBRIDA",
        "skills": [
            "Roadmap",
            "Agile",
            "Jira",
            "stakeholders",
            "backlog",
            "mvp",
           
        ],
        "salary": "30.000€ - 50.000€",
        "url": "https://jobs.kavehome.com/jobs/e-commerce-product-manager",
        "email": "amilena@kavehome.com",
    },
]

random.shuffle(JOBS)
